version: "3.7"
services:

  wordpress:
    depends_on:
      - mysql
      - phpmyadmin
    image: wordpress:latest
    container_name: carlajohnson
    ports:
      - "6002:80"
      - "7002:443"
    environment:
      WORDPRESS_DB_HOST: carlajohnson_db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: c@rl@
      WORDPRESS_DB_NAME: wordpress
    restart: always
    volumes:
      - "C:\\Projects\\carlajohnson\\html:/var/www/html"
      - "C:\\Projects\\carlajohnson\\config:/usr/docker-local/etc/php/conf.d"

  mysql:
    image: mariadb:latest
    container_name: carlajohnson_db
    volumes:
      -  "C:\\Projects\\carlajohnson\\data:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: c@rl@
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: c@rl@

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    depends_on: 
      - mysql
    container_name: carlajohnson_phpmyadmin
    ports:
      - "8182:80"
    environment:
      PMA_HOST: carlajohnson_db
      MYSQL_USERNAME: wordpress
      MYSQL_ROOT_PASSWORD: c@rl@

networks:
  default:
    external:
      name: nat